"""
Automated Abuse Report Generator.
Generates properly formatted reports for ISP abuse teams and CERT-In.
"""

from datetime import datetime, timezone

from app.ai.llm_client import llm_client


class AbuseReportGenerator:
    """
    Generates formatted abuse reports for different recipients.
    Uses LLM to fill in narrative sections.
    """

    def __init__(self):
        self.llm = llm_client

    def generate_isp_abuse_report(self, findings: dict) -> str:
        """Generate standard abuse report for hosting providers."""
        c2_list = findings.get("c2_infrastructure", [])
        c2_ip = c2_list[0].get("ip", "Unknown") if c2_list else "Unknown"

        narrative = self.llm.complete(
            system_prompt="Write a professional 2-paragraph abuse report to a hosting provider. Be specific about the evidence.",
            user_prompt=(
                f"C2 IP: {c2_ip}\n"
                f"Malware: {findings.get('malware_family', 'Unknown')}\n"
                f"Evidence: {findings.get('ai_analysis', {}).get('risk_assessment', {}).get('chain_of_reasoning', 'See attached report')}"
            )
        )

        now = datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')
        return f"""ABUSE REPORT — MALICIOUS HOSTING
Date: {now}
Reported IP: {c2_ip}
Case Reference: {findings.get('case_id', 'N/A')}

Dear Abuse Team,

{narrative}

Evidence Package: Available on request
SHA256 of malware sample: {findings.get('apk_sha256', 'N/A')}
PCAP evidence: Available

Requesting immediate suspension of the above IP address.

[Auto-generated by SecureX Platform]
"""

    def generate_certin_report(self, findings: dict) -> str:
        """Generate report formatted for CERT-In incident reporting."""
        c2_list = findings.get("c2_infrastructure", [])
        c2_ips = ", ".join(c.get("ip", "") for c in c2_list) or "N/A"
        c2_domains = ", ".join(c.get("domain", "") for c in c2_list if c.get("domain")) or "N/A"

        ai = findings.get("ai_analysis", {})
        risk = ai.get("risk_assessment", {})
        recs = risk.get("recommendations", [])

        return f"""CYBER SECURITY INCIDENT REPORT — CERT-In FORMAT
Incident Type: Malware / Fraudulent Mobile Application
Date of Discovery: {datetime.now(timezone.utc).strftime('%Y-%m-%d')}
Affected Sector: Banking / Financial Services

1. INCIDENT DESCRIPTION:
   {risk.get('chain_of_reasoning', 'See attached forensic report')}

2. INDICATORS OF COMPROMISE:
   SHA256: {findings.get('apk_sha256', 'N/A')}
   C2 IPs: {c2_ips}
   Domains: {c2_domains}

3. MALWARE CLASSIFICATION:
   Family: {findings.get('malware_family', 'Unknown')}
   Risk Score: {findings.get('threat_score', 'Unknown')}/100
   MITRE Techniques: {', '.join(findings.get('mitre_ttps', [])[:5])}

4. RECOMMENDED ACTIONS:
{chr(10).join('   - ' + r for r in recs)}

[Generated by SecureX · Evidence preserved in storage]
"""
